export const FATCH_LOGIN_AUTH_REQUEST = 'FATCH_LOGIN_AUTH_REQUEST';
export const FATCH_LOGIN_AUTH_SUCCESS = 'FATCH_LOGIN_AUTH_SUCCESS';
export const FATCH_LOGIN_AUTH_FAILURE = 'FATCH_LOGIN_AUTH_FAILURE';
export const FATCH_LOGOUT_AUTH = 'FATCH_LOGOUT_AUTH';

// USER 

//GET
export const FATCH_GET_ALL_USER_REQUEST = 'FATCH_GET_ALL_USER_REQUEST';
export const FATCH_GET_ALL_USER_SUCCESS = 'FATCH_GET_ALL_USER_SUCCESS';
export const FATCH_GET_ALL_USER_FAILURE = 'FATCH_GET_ALL_USER_FAILURE';

//DELETE

export const FATCH_DELETE_USER_REQUEST = 'FATCH_DELETE_USER_REQUEST';
export const FATCH_DELETE_USER_SUCCESS = 'FATCH_DELETE_USER_SUCCESS';
export const FATCH_DELETE_USER_FAILURE = 'FATCH_DELETE_USER_FAILURE';