export const FATCH_LOGIN_AUTH_REQUEST = 'FATCH_LOGIN_AUTH_REQUEST';
export const FATCH_LOGIN_AUTH_SUCCESS = 'FATCH_LOGIN_AUTH_SUCCESS';
export const FATCH_LOGIN_AUTH_FAILURE = 'FATCH_LOGIN_AUTH_FAILURE';